
name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'Automatic setup') || github.actor != 'github-classroom[bot]'"
    steps:
      - name: Cache Puppeteer
        uses: actions/cache@v2
        with:
          path: /home/runner/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-
            puppeteer-
      - name: Install puppeteer
        run: |
          npm install -g puppeteer
          google-chrome --version
      - uses: actions/checkout@v4
      - uses: GittyBitch/autograding@feature/feedback
